# -*- coding: utf-8 -*-
"""exercices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4fyyhUclugpbdlZvkbMuQNM7LVNoxop

**Exercice 1:** <br>
un magasin de reprographie pratique les tarifs suivants:<br>
$\star \,$ 0,15 euro l'unité jusqu'à 50 photocopies, <br>
$\star \,$ 0,10 euro au-delà. <br>
Définir une fonction prix qui prend en paramètre le nombre n de photocopies et renvoie le prix à payer.
"""



"""**Exercice 2:**<br> 
En mathématiques la factorielle d'un entier n désigne le produit <br>$n(n-1)(n-2)\,...\,2\times 1$ Ainsi factorielle de 3 vaut $3\times2\times1 = 6$.<br> Tester puis, corriger la fonction factorielle erronée ci-dessous.
"""

def factorielle(n):
    resultat = 1
    for i in range(n):
        resultat = resultat * i
    return resultat

factorielle(10)

"""**Exercice 3:** <br>Écrire une fonction renvoyant la première valeur de l'entier <br>$k$ à partir de laquelle $3^k > 10 000$."""



"""**Exercice 4:** <br> pour un individu l'imc est le quotien de la masse en kg par la taille en mètre au carré.<br> Ecrire une fonction qui renvoie :<br> - masse normale si l'imc < 25 <br> - en surpoids pour un imc entre 25 et 30 exclu.<br> - obésité pour un imc > 30"""



"""**Exercice 5:** <br> Completer le programme ci-dessous pour qu'il simule le lancer <br> d'un dé jusqu'à l'obtention d'un résultat supérieur à 4. <br> Le programme doit renvoyer le nombre de lancers nécessaires."""

from random import randint         

def attente():
	compteur = 0          # compteur du nombre d'itérations           
	d = 0                 # on initialise la variable d

  

	return "le 4 est sorti au bout de:", compteur, "lancers"